%% Import data from text file.
% Script for importing data from the following text file:
%
%    /zhome/f7/e/77392/02614_HPC/Week1/Assignment1/High-Performance-Computing/Project3/matmat/data/cpuDGEMM.txt
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2017/01/20 14:42:52

%% Initialize variables.
filename = '/zhome/f7/e/77392/02614_HPC/Week1/Assignment1/High-Performance-Computing/Project3/matmat/data/cpuDGEMM.txt';

%% Format string for each line of text:
%   column1: double (%f)
%	column2: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%10f%11f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', '', 'WhiteSpace', '',  'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Create output variable
cpuDGEMM = [dataArray{1:end-1}];
%% Clear temporary variables
clearvars filename formatSpec fileID dataArray ans;